apiVersion: apps/v1
kind: Deployment
metadata:
  name: minha-app-pedidos
spec:
  replicas: 2
  selector:
    matchLabels:
      app: minha-app-pedidos
  template:
    metadata:
      labels:
        app: minha-app-pedidos
    spec:
      tolerations:
        - key: "microservice"
          operator: "Equal"
          value: "pedidos"
          effect: "NoSchedule"
      containers:
        - name: minha-app-pedidos
          image: IMAGEM_PLACEHOLDER
          ports:
            - containerPort: 8080
          env:
            - name: AWS_REGION
              value: "us-east-1" # Altere se a sua regi√£o for outra
            - name: DYNAMODB_TABLE_NAME
              value: "Pedidos"