apiVersion: apps/v1
kind: Deployment
metadata:
  name: minha-app-pedidos
spec:
  replicas: 2
  selector:
    matchLabels:
      app: minha-app-pedidos
  template:
    metadata:
      labels:
        app: minha-app-pedidos
    spec:
      tolerations:
        - key: "microservice"
          operator: "Equal"
          value: "pedidos"
          effect: "NoSchedule"
      containers:
        - name: minha-app-pedidos
          image: IMAGEM_PLACEHOLDER
          ports:
            - containerPort: 8080
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: access-key
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: secret-key
            - name: AWS_REGION
              value: us-east-1
            - name: DYNAMODB_TABLE_NAME
              value: "Pedidos"
            - name: MERCADOPAGO_API_URL
              value: "https://api.mercadopago.com"
            - name: MERCADOPAGO_USER_ID
              value: "123456"
            - name: MERCADOPAGO_ACCESS_TOKEN
              value: "TEST-TOKEN"
            - name: MERCADOPAGO_POS_ID
              value: "POS01"
            - name: MERCADOPAGO_EXTERNAL_POS_ID
              value: "POS_EXT_01"
            - name: MERCADOPAGO_STORE_ID
              value: "STORE01"